# Generated by Django 5.1.1 on 2024-11-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_alter_comment_created_at_alter_todo_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='hehe',
            field=models.DateField(null=True),
        ),
    ]
