# Generated by Django 5.1.1 on 2024-11-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_todo_hehe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_on',
        ),
    ]
