# Generated by Django 5.1.1 on 2024-11-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_remove_todo_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='hehe',
            new_name='created_on',
        ),
    ]
