# Generated by Django 5.1.1 on 2024-11-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_rename_hehe_todo_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
    ]
