# Generated by Django 5.1.1 on 2024-11-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_alter_section_course_courserating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseRating',
        ),
    ]
