# Generated by Django 5.1.1 on 2024-11-08 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0020_courserating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='lms.student'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='specialization',
            field=models.TextField(null=True),
        ),
    ]
