# Generated by Django 5.1.1 on 2024-11-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0021_alter_courseenrollment_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
