# Generated by Django 5.1.1 on 2024-11-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0022_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
