# Generated by Django 5.1.1 on 2024-11-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0024_section_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('shoes', 'Shoes'), ('books', 'Books'), ('vouchers', 'Gift Cards & Vouchers'), ('merchandise', 'Merchandise'), ('tech', 'Tech'), ('health', 'Health & Wellness')], max_length=11, null=True)),
                ('productName', models.CharField(max_length=100)),
                ('productImage', models.CharField(blank=True, max_length=255, null=True)),
                ('productPrice', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
