# Generated by Django 5.1.1 on 2024-11-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0025_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rewardPoints',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
