# Generated by Django 5.1.1 on 2024-11-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0026_student_rewardpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='total_marks',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='total_questions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
