# Generated by Django 5.1.1 on 2024-11-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0027_remove_assessment_total_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='student_assessment',
        ),
        migrations.RenameField(
            model_name='studentassessment',
            old_name='student',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
    ]
