# Generated by Django 5.1.1 on 2024-11-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0028_remove_studentanswer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='banner',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tutor',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
