# Generated by Django 5.1.1 on 2024-11-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0029_tutor_banner_tutor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
