# Generated by Django 5.1.1 on 2024-11-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0032_alter_section_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('reading', 'Reading'), ('video', 'Video'), ('assessment', 'Assessment')], max_length=10, null=True),
        ),
    ]
