# Generated by Django 5.1.1 on 2024-11-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0035_alter_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='program',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year_of_study',
        ),
        migrations.AddField(
            model_name='student',
            name='banner',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
