# Generated by Django 5.1.1 on 2024-11-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0037_alter_courserating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
