# Generated by Django 5.1.1 on 2024-11-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_assignment_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
