# Generated by Django 5.1.1 on 2024-11-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_alter_assignment_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
